name: blogify
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  json_annotation: ^4.9.0

  # Responsive Design
  flutter_screenutil: ^5.9.3

  # Util
  easy_localization: ^3.0.7
  i_toast: ^0.0.6
  hive: ^2.2.3
  encrypt: 5.0.1
  path_provider: ^2.1.5
  # Network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  plugin_platform_interface: ^2.1.8
  path_provider_platform_interface: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
